version: "3"

services:
  app:
    build: ./app
    tty: true # https://github.com/facebook/create-react-app/issues/8688
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules

  api:
    build: ./api
    ports:
      - "8500:8500"
    volumes:
      - ./api:/api
      - /api/node_modules
